# YDLIDAR的ROS2驱动节点配置参数
ydlidar_ros2_driver_node:
  ros__parameters:
    # 指定LIDAR设备的串口路径
    port: /dev/lidar
    # 定义LIDAR数据在ROS中的参考坐标系
    frame_id: base_laser_link
    # 忽略特定角度范围的配置，用于屏蔽不需要的数据
    ignore_array: ""
    # 设置串口通信的波特率
    baudrate: 115200
    # 指定LIDAR的类型，不同的LIDAR型号可能需要不同的驱动逻辑
    lidar_type: 1
    # 设备连接类型，通常为0表示串口连接
    device_type: 0
    # 采样率，决定数据采集的频率
    sample_rate: 3
    # 异常检测次数，用于提高数据的可靠性
    abnormal_check_count: 4
    # 固定分辨率模式，确保每次测量的角度间隔一致
    fixed_resolution: true
    # 数据反转功能，适用于需要反转LIDAR数据的场景
    reversion: true
    # 数据翻转功能，适用于需要翻转LIDAR数据的场景
    inverted: true
    # 自动重连功能，增强系统稳定性
    auto_reconnect: true
    # 单通道模式，适用于只使用一个LIDAR通道的场景
    isSingleChannel: true
    # 强度输出功能，开启后LIDAR将提供测量点的反射强度信息
    intensity: false
    # 支持通过DTR线控制电机，适用于特定的LIDAR型号
    support_motor_dtr: true
    angle_max: 180.0
    angle_min: -180.0
    range_max: 12.0
    range_min: 0.1
    # 数据更新频率，决定LIDAR数据的发布速率
    frequency: 10.0
    # 无效范围是否为无穷远，用于处理某些LIDAR在测量无效时返回无穷大值的情况
    invalid_range_is_inf: false
