image_width: 640
image_height: 480
camera_name: rgb_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [521.1447 ,   0.     , 307.18932,
           0.     , 521.7976 , 236.38   ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.006250, -0.043833, -0.000910, -0.001254, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [518.10187,   0.     , 305.67996,   0.     ,
           0.     , 520.40771, 235.55581,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
